[build-system]
requires = ["setuptools >= 65.4.0", "setuptools_scm[toml]>=7.0.5"]
build-backend = "setuptools.build_meta"

[project]
name = "spline_replacer"
authors = [
  { name="Jonathan Shimwell", email="mail@jshimwell.com" },
]
license = {file = "LICENSE.txt"}
description = "Converts CAD files to a DAGMC h5m file"
readme = "README.md"
requires-python = ">=3.8"
keywords = ["spline", "csg", "polylines", "monte", "carlo"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "cadquery",
]
dynamic = ["version"]


[tool.setuptools_scm]
write_to = "src/_version.py"


[project.optional-dependencies]
tests = [
    "pytest",
]

[project.urls]
"Homepage" = "https://github.com/fusion-energy/spline_replacer"
"Bug Tracker" = "https://github.com/fusion-energy/spline_replacer/issues"

[tool.setuptools]
package-dir = {"" = "src"}
